PCGuardTutorial = CreateDialog(function ()
    Talk("희위쌤","첫번째 선수는 'R'키를 눌러 공격을 막을 수 있다.","HwiwiT")
    Talk("희위쌤","두번째 선수는 마우스의 휠을 클릭하여 공격을 막을 할 수 있다.","HwiwiT")
    Talk("희위쌤","대신 공격을 막는 것은 타이밍이 생명입니다, 여러분.","HwiwiT")
    Talk("희위쌤","파이팅 하시라.","HwiwiT")
end)

NoriBoxGuardTutorial = CreateDialog(function ()
    Talk("희위쌤","양측 선수는 <color=#008A32>하단 중앙의 초록색 버튼</color>을 눌러 공격을 막을 수 있다.","HwiwiT")
    Talk("희위쌤","대신 공격을 막는 것은 타이밍이 생명입니다, 여러분.","HwiwiT")
    Talk("희위쌤","파이팅 하시라.","HwiwiT")
end)